spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/parqueadero
    username: root
    password: 12345678
  jpa:
    hibernate.ddl-auto: validate
    generate-ddl: true
 
 
server: 
  error:
    whitelabel:
      enabled: false
  port: 8180 
